### ISSUE TITLE
Normal Suggestions

### ISSUE THREAD

**Issue by lcbiplove** [allwcons/portfolio#2]
Suggestions I have:
- Favicon to your site
- In Process and Finished block looks quite off
- Name of your projects should either be in capitalized or small but consistent throughout
- Theme does not seem to work
- Spelling of title: Skectjs library

**Comment by allwcons** [comment]
nice idea

**Comment by allwcons** [comment]
theme should work

**Comment by allwcons** [comment]
if browser has theme preference then it may be affected

**Comment by allwcons** [comment]
> if browser has theme preference then it may be affected

now theme will overide the chrome prefer theme

**Comment by allwcons** [comment]
now only second enhancement in given is need to deal with.

**Comment by allwcons** [comment]
can you elaborate further on second enhancement?
I am having hard time to understand your second enhancement

**Comment by lcbiplove** [comment]
@allwcons  Theme works perfectly in chrome. But, it does not in *Firefox* which I am using:
* Version 92.0.1 (64-bit)

**Comment by allwcons** [comment]
![second](https://user-images.githubusercontent.com/76528377/134815422-aff255b1-d169-4110-b0fe-4925f8721ffe.JPG)

it working
please re-check

**Comment by allwcons** [comment]
now block desgin is solved in firefox.

**Comment by lcbiplove** [comment]
@allwcons Still not working. Please check it the version I am using.

**Comment by allwcons** [comment]
It changed some code. can you check it again?
